[
  {
    "problem_id": "amc12_2000_p1",
    "dataset": "minif2f",
    "error_message": "'Timed Out'",
    "error_type": "TimeoutError",
    "traceback": "Traceback (most recent call last):\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 969, in process_problem\n    steps = self.decompose_problem(problem)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 55, in decompose_problem\n    _hole_content, hole_list = self.generate_in_place_holes(problem)\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 825, in generate_in_place_holes\n    return self._process_content_for_holes(problem_content, header_content)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 328, in _process_content_for_holes\n    result = self.lean_verifier.run_with_header(header_content, cmd_str, all_tactics=True)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_solver.py\", line 1003, in run_with_header\n    ret = run_with_timeout()\n          ^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 82, in new_function\n    return function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_solver.py\", line 1000, in run_with_timeout\n    return self.server.run(Command(cmd=input_content, env=env, **kwargs))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 239, in run\n    result_dict = self.run_dict(request=request_dict, verbose=verbose, timeout=timeout, **kwargs)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 177, in run_dict\n    raw_output = self._execute_cmd_in_repl(json_query, verbose, timeout)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 143, in _execute_cmd_in_repl\n    t.join(timeout)\n  File \"/home/matheye/anaconda3/lib/python3.12/threading.py\", line 1149, in join\n    self._wait_for_tstate_lock()\n  File \"/home/matheye/anaconda3/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n    if lock.acquire(block, timeout):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 69, in handler\n    _raise_exception(timeout_exception, exception_message)\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 45, in _raise_exception\n    raise exception()\ntimeout_decorator.timeout_decorator.TimeoutError: 'Timed Out'\n",
    "processing_time_seconds": 90.217745,
    "timestamp": "2025-06-18T22:31:29.953588"
  },
  {
    "problem_id": "amc12_2000_p12",
    "dataset": "minif2f",
    "error_message": "maximum recursion depth exceeded",
    "error_type": "RecursionError",
    "traceback": "Traceback (most recent call last):\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 969, in process_problem\n    steps = self.decompose_problem(problem)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 55, in decompose_problem\n    _hole_content, hole_list = self.generate_in_place_holes(problem)\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 825, in generate_in_place_holes\n    return self._process_content_for_holes(problem_content, header_content)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 377, in _process_content_for_holes\n    process_nodes_for_holes(top_level_nodes)\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 362, in process_nodes_for_holes\n    process_nodes_for_holes(node.subhaves)\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 362, in process_nodes_for_holes\n    process_nodes_for_holes(node.subhaves)\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 362, in process_nodes_for_holes\n    process_nodes_for_holes(node.subhaves)\n  [Previous line repeated 990 more times]\nRecursionError: maximum recursion depth exceeded\n",
    "processing_time_seconds": 43.543585,
    "timestamp": "2025-06-18T22:32:13.498245"
  },
  {
    "problem_id": "amc12a_2021_p19",
    "dataset": "minif2f",
    "error_message": "'Timed Out'",
    "error_type": "TimeoutError",
    "traceback": "Traceback (most recent call last):\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 933, in process_problem\n    original_verification_pass, verification_error = self.verify_lean_code(header_content, original_content, return_error_string=True)\n                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 249, in verify_lean_code\n    result = self.lean_verifier.run_with_header(header, content)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_solver.py\", line 1003, in run_with_header\n    ret = run_with_timeout()\n          ^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 82, in new_function\n    return function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_solver.py\", line 1000, in run_with_timeout\n    return self.server.run(Command(cmd=input_content, env=env, **kwargs))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 239, in run\n    result_dict = self.run_dict(request=request_dict, verbose=verbose, timeout=timeout, **kwargs)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 177, in run_dict\n    raw_output = self._execute_cmd_in_repl(json_query, verbose, timeout)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 143, in _execute_cmd_in_repl\n    t.join(timeout)\n  File \"/home/matheye/anaconda3/lib/python3.12/threading.py\", line 1149, in join\n    self._wait_for_tstate_lock()\n  File \"/home/matheye/anaconda3/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n    if lock.acquire(block, timeout):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 69, in handler\n    _raise_exception(timeout_exception, exception_message)\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 45, in _raise_exception\n    raise exception()\ntimeout_decorator.timeout_decorator.TimeoutError: 'Timed Out'\n",
    "processing_time_seconds": 67.348822,
    "timestamp": "2025-06-18T22:33:42.122197"
  },
  {
    "problem_id": "algebra_apbpceq2_abpbcpcaeq1_aleq1on3anbleq1ancleq4on3",
    "dataset": "minif2f",
    "error_message": "'Timed Out'",
    "error_type": "TimeoutError",
    "traceback": "Traceback (most recent call last):\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 933, in process_problem\n    original_verification_pass, verification_error = self.verify_lean_code(header_content, original_content, return_error_string=True)\n                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 249, in verify_lean_code\n    result = self.lean_verifier.run_with_header(header, content)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_solver.py\", line 1003, in run_with_header\n    ret = run_with_timeout()\n          ^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 82, in new_function\n    return function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_solver.py\", line 1000, in run_with_timeout\n    return self.server.run(Command(cmd=input_content, env=env, **kwargs))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 239, in run\n    result_dict = self.run_dict(request=request_dict, verbose=verbose, timeout=timeout, **kwargs)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 177, in run_dict\n    raw_output = self._execute_cmd_in_repl(json_query, verbose, timeout)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 143, in _execute_cmd_in_repl\n    t.join(timeout)\n  File \"/home/matheye/anaconda3/lib/python3.12/threading.py\", line 1149, in join\n    self._wait_for_tstate_lock()\n  File \"/home/matheye/anaconda3/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n    if lock.acquire(block, timeout):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 69, in handler\n    _raise_exception(timeout_exception, exception_message)\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 45, in _raise_exception\n    raise exception()\ntimeout_decorator.timeout_decorator.TimeoutError: 'Timed Out'\n",
    "processing_time_seconds": 66.480177,
    "timestamp": "2025-06-18T22:47:09.562827"
  },
  {
    "problem_id": "amc12a_2021_p22",
    "dataset": "minif2f",
    "error_message": "Problem amc12a_2021_p22 skipped: code too long (631 lines > 400 lines limit)",
    "failure_reason": "code_too_long",
    "code_lines": 631,
    "processing_time_seconds": 0.000139,
    "timestamp": "2025-06-18T22:49:49.808167"
  },
  {
    "problem_id": "imo_1992_p1",
    "dataset": "minif2f",
    "error_message": "Problem imo_1992_p1 skipped: code too long (580 lines > 400 lines limit)",
    "failure_reason": "code_too_long",
    "code_lines": 580,
    "processing_time_seconds": 0.000148,
    "timestamp": "2025-06-18T22:54:51.356154"
  },
  {
    "problem_id": "imo_1965_p2",
    "dataset": "minif2f",
    "error_message": "'Timed Out'",
    "error_type": "TimeoutError",
    "traceback": "Traceback (most recent call last):\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 933, in process_problem\n    original_verification_pass, verification_error = self.verify_lean_code(header_content, original_content, return_error_string=True)\n                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 249, in verify_lean_code\n    result = self.lean_verifier.run_with_header(header, content)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_solver.py\", line 1003, in run_with_header\n    ret = run_with_timeout()\n          ^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 82, in new_function\n    return function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_solver.py\", line 1000, in run_with_timeout\n    return self.server.run(Command(cmd=input_content, env=env, **kwargs))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 239, in run\n    result_dict = self.run_dict(request=request_dict, verbose=verbose, timeout=timeout, **kwargs)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 177, in run_dict\n    raw_output = self._execute_cmd_in_repl(json_query, verbose, timeout)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/lean_interact/server.py\", line 143, in _execute_cmd_in_repl\n    t.join(timeout)\n  File \"/home/matheye/anaconda3/lib/python3.12/threading.py\", line 1149, in join\n    self._wait_for_tstate_lock()\n  File \"/home/matheye/anaconda3/lib/python3.12/threading.py\", line 1169, in _wait_for_tstate_lock\n    if lock.acquire(block, timeout):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 69, in handler\n    _raise_exception(timeout_exception, exception_message)\n  File \"/home/matheye/anaconda3/lib/python3.12/site-packages/timeout_decorator/timeout_decorator.py\", line 45, in _raise_exception\n    raise exception()\ntimeout_decorator.timeout_decorator.TimeoutError: 'Timed Out'\n",
    "processing_time_seconds": 66.871336,
    "timestamp": "2025-06-18T23:08:51.313974"
  },
  {
    "problem_id": "aime_1984_p7",
    "dataset": "minif2f",
    "error_message": "Problem aime_1984_p7 skipped: code too long (2107 lines > 400 lines limit)",
    "failure_reason": "code_too_long",
    "code_lines": 2107,
    "processing_time_seconds": 0.000294,
    "timestamp": "2025-06-18T23:25:37.009307"
  },
  {
    "problem_id": "aime_1994_p3",
    "dataset": "minif2f",
    "error_message": "Problem aime_1994_p3 skipped: code too long (732 lines > 400 lines limit)",
    "failure_reason": "code_too_long",
    "code_lines": 732,
    "processing_time_seconds": 0.000111,
    "timestamp": "2025-06-18T23:27:16.780083"
  },
  {
    "problem_id": "mathd_numbertheory_541",
    "dataset": "minif2f",
    "error_message": "maximum recursion depth exceeded",
    "error_type": "RecursionError",
    "traceback": "Traceback (most recent call last):\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 969, in process_problem\n    steps = self.decompose_problem(problem)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 55, in decompose_problem\n    _hole_content, hole_list = self.generate_in_place_holes(problem)\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 825, in generate_in_place_holes\n    return self._process_content_for_holes(problem_content, header_content)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 377, in _process_content_for_holes\n    process_nodes_for_holes(top_level_nodes)\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 362, in process_nodes_for_holes\n    process_nodes_for_holes(node.subhaves)\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 362, in process_nodes_for_holes\n    process_nodes_for_holes(node.subhaves)\n  File \"/home/matheye/lean-pl-fix/decompose_hole_merge_pipeline.py\", line 362, in process_nodes_for_holes\n    process_nodes_for_holes(node.subhaves)\n  [Previous line repeated 990 more times]\nRecursionError: maximum recursion depth exceeded\n",
    "processing_time_seconds": 26.713111,
    "timestamp": "2025-06-18T23:31:09.984467"
  }
]